bluetooth: Don't include <cutils/properties.h>.
It's not needed an causes some errors:
system/bt/osi/include/properties.h:23:9: error: 'PROPERTY_VALUE_MAX' macro redefined [-Werror,-Wmacro-redefined]
        ^
system/core/include/cutils/properties.h:37:9: note: previous definition is here
        ^
1 error generated.

Change-Id: I1523a1e457fce496e1cebdd9edb026dc9dd0f742